version: "2.0"

services:

  zaas-halo-py-api:
    image: property_analytics:1.0.0
    container_name: INTICS
    hostname: intics.copro
    build: .
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Kolkata"
    command: python manage.py runserver 8000
    volumes:
      - ./source-of-truth:/app/source-of-truth
      - ./tmp:/tmp
    networks:
      halo-dl-net:

networks:
  halo-dl-net:
    external: true
